version: '3'
services:
    authentication:
        container_name: authentication-service
        restart: always
        build: .
        ports:
            - '8000:8000'
        external_links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'