version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
    authentication:
        container_name: authentication-service
        environment:
            ENVIRONMENT: PROD
        restart: always
        build: 
            context: ./microservices
            dockerfile: authenticator.Dockerfile
        ports:
            - '8000:8000'
        depends_on:
            - mongo
        external_links:
            - mongo
    admin:
        container_name: admin-service
        environment:
            ENVIRONMENT: PROD
        restart: always
        build: 
            context: ./microservices
            dockerfile: admin.Dockerfile
        ports:
            - '8001:8001'
        depends_on:
            - mongo
        external_links:
            - mongo
    dashboard:
        container_name: dashboard-service
        environment:
            ENVIRONMENT: PROD
        restart: always
        build: 
            context: ./microservices
            dockerfile: dashboard.Dockerfile
        ports:
            - '8002:8002'
        depends_on:
            - mongo
        external_links:
            - mongo
    frontend:
        container_name: frontend
        environment:
            ENVIRONMENT: PROD
        restart: always
        build: 
            context: ./frontend
            dockerfile: frontend.Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - authentication
            - admin
            - dashboard
        external_links:
            - authentication
            - admin
            - dashboard