version: '3'
services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
    authentication:
        container_name: authentication-service
        restart: always
        build: ./authenticator
        ports:
            - '8000:8000'
        external_links:
            - mongo
    admin:
        container_name: admin-service
        restart: always
        build: ./admin
        ports:
            - '8001:8001'
        external_links:
            - mongo
            - authentication
    dashboard:
        container_name: dashboard-service
        restart: always
        build: ./dashboard
        ports:
            - '8002:8002'
        external_links:
            - mongo
            - authentication